//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hospital.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати запис.
        /// </summary>
        public static string AddNewPatientRecord {
            get {
                return ResourceManager.GetString("AddNewPatientRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сума.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік народження.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to р.н..
        /// </summary>
        public static string BirthYearShortForm {
            get {
                return ResourceManager.GetString("BirthYearShortForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to м.Мелітополь, вул.Героїв України, 27.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фінансовий.
        /// </summary>
        public static string DateRangeReport {
            get {
                return ResourceManager.GetString("DateRangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частка лікаря.
        /// </summary>
        public static string DoctorAmount {
            get {
                return ResourceManager.GetString("DoctorAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лікар.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати останній запис.
        /// </summary>
        public static string EditLastPatientRecord {
            get {
                return ResourceManager.GetString("EditLastPatientRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жіноча.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to З.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПП «Невромед».
        /// </summary>
        public static string FullCompanyName {
            get {
                return ResourceManager.GetString("FullCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стать.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Згенерувати.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частка клініки.
        /// </summary>
        public static string HospitalAmount {
            get {
                return ResourceManager.GetString("HospitalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхідні дані.
        /// </summary>
        public static string InputData {
            get {
                return ResourceManager.GetString("InputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Головне меню.
        /// </summary>
        public static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чоловіча.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ліцензія МОЗ України №АГ597651.
        /// </summary>
        public static string MinistryOfHealthCareLicense {
            get {
                return ResourceManager.GetString("MinistryOfHealthCareLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість пацієнтів.
        /// </summary>
        public static string NumberOfPatients {
            get {
                return ResourceManager.GetString("NumberOfPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П І Б.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this patient was not found in the system.
        /// </summary>
        public static string PatientNotFound {
            get {
                return ResourceManager.GetString("PatientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Записи пацієнтів.
        /// </summary>
        public static string PatientRecords {
            get {
                return ResourceManager.GetString("PatientRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По пацієнту.
        /// </summary>
        public static string PatientReport {
            get {
                return ResourceManager.GetString("PatientReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this patient was not at the clinic during the specified period.
        /// </summary>
        public static string PatientWasNotAtClinicDuringSpecifiedPeriod {
            get {
                return ResourceManager.GetString("PatientWasNotAtClinicDuringSpecifiedPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Друк.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роздрукувати бланк для висновку.
        /// </summary>
        public static string PrintBasicPatientInformation {
            get {
                return ResourceManager.GetString("PrintBasicPatientInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звіти.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результати.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть дату.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За певну дату.
        /// </summary>
        public static string SpecificDateReport {
            get {
                return ResourceManager.GetString("SpecificDateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місто/село.
        /// </summary>
        public static string TownOrVillage {
            get {
                return ResourceManager.GetString("TownOrVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка: {0}!.
        /// </summary>
        public static string ValidationErrorTemplate {
            get {
                return ResourceManager.GetString("ValidationErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
    }
}
